# Generated by Django 3.2 on 2023-02-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ak_jol_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('answer', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_jol_user.author')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('image', models.ImageField(blank=True, upload_to='photos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_jol_user.author')),
            ],
        ),
        migrations.CreateModel(
            name='GetAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdd.answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ak_jol_user.author')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdd.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdd.question'),
        ),
    ]
