# Generated by Django 3.2 on 2023-02-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetAnswer',
        ),
    ]
