# Generated by Django 3.2 on 2023-02-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdd', '0003_auto_20230228_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogNamber',
            field=models.IntegerField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
