# Generated by Django 3.2 on 2023-02-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdd', '0005_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='photos/blog'),
        ),
    ]
